### ISSUE TITLE
Adding API capabilities in the python record model wrappers

### ISSUE THREAD

**Issue by niklaskristiansen** [sapiosciences/sapio-py-tutorials#5]
Currently when trying to use the python API it can be quite difficult to do exactly what you want it to do. There's documentation on it but obviously a lot of flexibility in the software as a whole so adopting it to a specific use-case can be hard and I usually find myself writing custom code for each data type.

It would be fantastic if as part of the python wrapper with the data models it also contained class methods to push data as well as pull data from Sapio itself (perhaps even update certain fields in an existing record). I realize this would require authentication as well as a base URL or something like that as inputs but it would make using these wrappers to interact with the system a lot easier.

Nik

**Comment by yechenqiao** [comment]
Hi.

In our design the data model is separate from the controllers. The data models should not be specific to a connection context, and it is the server that handles the nuts and bolts of the implementation.

I am not sure what specific you meant by "python wrappers with data models". For tutorials on connecting with existing data, please review [Tutorial 1](https://github.com/sapiosciences/sapio-py-tutorials/blob/master/1_query_data_records.ipynb) and [Tutorial 2](https://github.com/sapiosciences/sapio-py-tutorials/blob/master/2_manipulate_data_records.ipynb). They already have existing examples with a base URL connections baked into the juypter notebook. And a more stateful approach of this is discussed in [Tutorial 9](https://github.com/sapiosciences/sapio-py-tutorials/blob/master/9_python_record_models.ipynb).

**Comment by niklaskristiansen** [comment]
Hello, 

I recently became aware of the capability of downloading a big python file with python class representation of all the sapio data types in the system. The button looks like this under -> App setup -> Manage Rules and Webhooks -> Webservice API: 
![image](https://github.com/sapiosciences/sapio-py-tutorials/assets/111470801/c4684910-aa32-4dfe-979b-d12b8cad44b2)

This is where class functions to push/pull data could be useful in addition to just the class definitions

**Comment by yechenqiao** [comment]
Hello.

Yes, the use of this button is covered in Tutorial 9. And the methods to push/pull data using these classes are also discussed there as well.
